In [44]:
import sympy as sp
import numpy as np

def check_dependance(S,dim):
    var=sp.symbols(f'a:{len(S)}')
    m = 0
    #print(var)
    for i,v in enumerate(var):
        m=m+v*S[i]
    scalars=sp.solve(m,var)
    print(scalars)
    flag = 0
    for x in scalars:
        if scalars[x] != 0:
            flag = 1
    if flag == 0:
        print("The vectors are linearly independent")
        if dim==len(scalars):
            
            print(f"The given set{S} is a basis of the vector space\n")
        else:
            print(f"The given set{S} is not a basis of the vector space\n")
    elif flag == 1:
        print(f"The{S} vectors are linearly dependent and hence cannot be a basis\n")    
S = np.array([(1,0,0,-1),(0,1,0,-1),(0,0,1,-1),(0,0,0,1)])
check_dependance(S,4)
01
S=np.array([(1,1,0),(0,1,1),(2,1,-1)])
check_dependance(S,3)

x = sp.symbols('x')
S = np.array([1+x+x**2,x+x**2,x**2])
check_dependance(S,3)

{a0: 0, a1: 0, a2: 0, a3: 0}
The vectors are linearly independent
The given set[[ 1  0  0 -1]
 [ 0  1  0 -1]
 [ 0  0  1 -1]
 [ 0  0  0  1]] is a basis of the vector space

{a0: -2*a2, a1: a2}
The[[ 1  1  0]
 [ 0  1  1]
 [ 2  1 -1]] vectors are linearly dependent and hence cannot be a basis

{a0: 0, a1: 0, a2: 0}
The vectors are linearly independent
The given set[x**2 + x + 1 x**2 + x x**2] is a basis of the vector space

